[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"

[[headers]]
  for = "/version.json"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"
